[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[prune]
  go-tests = true
  unused-packages = true
